# Wake up your Heroku application by using Github Action
name: AutoWakeupHeroku2

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "*/25 * 15-31 * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # Start by user
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python # install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests # install requests
      run: |
        pip install requests
    - name: Waking  # Read sites
      env: 
        $CONFIG_SITE: ${{ secrets.Site2 }} # Get site from secrets
      run: | 
        python run.py ${{ secrets.Site2 }}
