# Wake up your Heroku application by using Github Action
name: AutoWakeupHeroku2

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "*/19 * 15/* * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # Start by user
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python # install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests # install requests
      run: |
        pip install requests
    - name: Waking  # Read sites
      env: 
        $CONFIG_SITE: ${{ secrets.Site2 }} # Get site from secrets
      run: | 
        python run.py ${{ secrets.Site2 }}
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Commit # update log to Github
      run: |
        git config --global user.email GamerPesy@outlook.com
        git config --global user.name Haikido
        git add .
        git commit -m "Sites have been woke up successfully" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
